"""デモ用レストランデータ（東京エリア）.

実際のプロダクションでは食べログ・ホットペッパー・Google APIから取得するが、
デモ用にリアルな構造のモックデータを用意する。
"""

GENRES = [
    "和食", "寿司", "焼肉", "イタリアン", "フレンチ",
    "中華", "韓国料理", "居酒屋", "ラーメン", "カフェ",
    "タイ料理", "インド料理", "スペイン料理", "ビストロ", "鉄板焼き",
]

ATMOSPHERES = [
    "おしゃれ", "落ち着いた", "にぎやか", "デート向き", "隠れ家",
    "カジュアル", "高級感", "アットホーム", "モダン", "和モダン",
    "テラス席あり", "夜景が見える", "個室あり", "大人数OK", "静か",
]

AREAS = [
    "渋谷", "新宿", "恵比寿", "表参道", "六本木",
    "銀座", "池袋", "目黒", "中目黒", "代官山",
    "青山", "赤坂", "麻布十番", "白金", "丸の内",
]

MOCK_RESTAURANTS = [
    {
        "id": "r001",
        "name": "鮨 さいとう",
        "genre": "寿司",
        "sub_genre": "江戸前寿司",
        "area": "六本木",
        "address": "東京都港区六本木1-4-5",
        "lat": 35.6627,
        "lng": 139.7380,
        "price_min": 15000,
        "price_max": 30000,
        "price_label": "¥15,000〜¥30,000",
        "atmosphere_tags": ["高級感", "落ち着いた", "カウンター"],
        "photos": [],
        "reviews": [
            {"source": "tabelog", "source_label": "食べログ", "rating": 4.70, "review_count": 892},
            {"source": "google", "source_label": "Google", "rating": 4.6, "review_count": 1243},
            {"source": "hotpepper", "source_label": "ホットペッパー", "rating": 4.5, "review_count": 210},
        ],
        "reservation_status": "few",
        "reservation_label": "残りわずか",
        "open_hours": "17:00〜23:00",
        "closed_days": "日曜・祝日",
        "capacity": 12,
        "has_private_room": False,
        "smoking": "禁煙",
        "description": "ミシュラン三つ星の名店。厳選されたネタと匠の技が織りなす至高の江戸前寿司。",
        "features": ["ミシュラン三つ星", "要予約", "カウンター席のみ"],
        "distance_meters": 0,
        "walk_minutes": 0,
    },
    {
        "id": "r002",
        "name": "焼肉ジャンボ 篠崎本店",
        "genre": "焼肉",
        "sub_genre": "黒毛和牛",
        "area": "渋谷",
        "address": "東京都渋谷区渋谷3-15-2",
        "lat": 35.6580,
        "lng": 139.7016,
        "price_min": 8000,
        "price_max": 15000,
        "price_label": "¥8,000〜¥15,000",
        "atmosphere_tags": ["にぎやか", "大人数OK", "カジュアル"],
        "photos": [],
        "reviews": [
            {"source": "tabelog", "source_label": "食べログ", "rating": 3.85, "review_count": 1567},
            {"source": "google", "source_label": "Google", "rating": 4.3, "review_count": 3421},
            {"source": "hotpepper", "source_label": "ホットペッパー", "rating": 4.1, "review_count": 876},
        ],
        "reservation_status": "available",
        "reservation_label": "予約可能",
        "open_hours": "17:00〜24:00",
        "closed_days": "不定休",
        "capacity": 80,
        "has_private_room": True,
        "smoking": "分煙",
        "description": "A5ランク黒毛和牛を豪快に。特製タレと厳選肉のハーモニーが人気の実力店。",
        "features": ["A5和牛", "個室あり", "飲み放題あり"],
        "distance_meters": 0,
        "walk_minutes": 0,
    },
    {
        "id": "r003",
        "name": "リストランテ アクアパッツァ",
        "genre": "イタリアン",
        "sub_genre": "南イタリア料理",
        "area": "表参道",
        "address": "東京都港区南青山3-18-1",
        "lat": 35.6654,
        "lng": 139.7149,
        "price_min": 10000,
        "price_max": 20000,
        "price_label": "¥10,000〜¥20,000",
        "atmosphere_tags": ["おしゃれ", "デート向き", "モダン"],
        "photos": [],
        "reviews": [
            {"source": "tabelog", "source_label": "食べログ", "rating": 4.12, "review_count": 634},
            {"source": "google", "source_label": "Google", "rating": 4.4, "review_count": 987},
            {"source": "hotpepper", "source_label": "ホットペッパー", "rating": 4.3, "review_count": 445},
        ],
        "reservation_status": "available",
        "reservation_label": "予約可能",
        "open_hours": "11:30〜14:30 / 18:00〜22:00",
        "closed_days": "月曜",
        "capacity": 45,
        "has_private_room": True,
        "smoking": "禁煙",
        "description": "南イタリアの太陽を感じる本格派。自家製パスタと魚介料理が絶品。",
        "features": ["テラス席", "コース料理", "記念日対応"],
        "distance_meters": 0,
        "walk_minutes": 0,
    },
    {
        "id": "r004",
        "name": "龍天門",
        "genre": "中華",
        "sub_genre": "広東料理",
        "area": "赤坂",
        "address": "東京都港区赤坂2-14-3",
        "lat": 35.6729,
        "lng": 139.7388,
        "price_min": 6000,
        "price_max": 12000,
        "price_label": "¥6,000〜¥12,000",
        "atmosphere_tags": ["高級感", "落ち着いた", "個室あり"],
        "photos": [],
        "reviews": [
            {"source": "tabelog", "source_label": "食べログ", "rating": 3.92, "review_count": 478},
            {"source": "google", "source_label": "Google", "rating": 4.2, "review_count": 1876},
            {"source": "hotpepper", "source_label": "ホットペッパー", "rating": 4.0, "review_count": 321},
        ],
        "reservation_status": "available",
        "reservation_label": "予約可能",
        "open_hours": "11:30〜14:30 / 17:30〜21:30",
        "closed_days": "無休",
        "capacity": 120,
        "has_private_room": True,
        "smoking": "禁煙",
        "description": "ホテル内の本格広東料理。点心から大皿まで、熟練の技が光る。",
        "features": ["ホテルレストラン", "個室多数", "コース充実"],
        "distance_meters": 0,
        "walk_minutes": 0,
    },
    {
        "id": "r005",
        "name": "ビストロ エガリテ",
        "genre": "フレンチ",
        "sub_genre": "ビストロ",
        "area": "代官山",
        "address": "東京都渋谷区猿楽町10-1",
        "lat": 35.6499,
        "lng": 139.7018,
        "price_min": 5000,
        "price_max": 10000,
        "price_label": "¥5,000〜¥10,000",
        "atmosphere_tags": ["カジュアル", "おしゃれ", "デート向き", "アットホーム"],
        "photos": [],
        "reviews": [
            {"source": "tabelog", "source_label": "食べログ", "rating": 3.78, "review_count": 312},
            {"source": "google", "source_label": "Google", "rating": 4.5, "review_count": 654},
            {"source": "hotpepper", "source_label": "ホットペッパー", "rating": 4.2, "review_count": 189},
        ],
        "reservation_status": "available",
        "reservation_label": "予約可能",
        "open_hours": "11:30〜14:00 / 18:00〜22:30",
        "closed_days": "水曜",
        "capacity": 32,
        "has_private_room": False,
        "smoking": "禁煙",
        "description": "気軽に楽しめる本格フレンチビストロ。ワインとの相性抜群の季節の料理。",
        "features": ["ワイン充実", "テラス席", "ランチコースあり"],
        "distance_meters": 0,
        "walk_minutes": 0,
    },
    {
        "id": "r006",
        "name": "韓国料理 ハヌリ 新宿店",
        "genre": "韓国料理",
        "sub_genre": "サムギョプサル",
        "area": "新宿",
        "address": "東京都新宿区歌舞伎町1-23-5",
        "lat": 35.6938,
        "lng": 139.7034,
        "price_min": 3000,
        "price_max": 5000,
        "price_label": "¥3,000〜¥5,000",
        "atmosphere_tags": ["にぎやか", "カジュアル", "大人数OK"],
        "photos": [],
        "reviews": [
            {"source": "tabelog", "source_label": "食べログ", "rating": 3.55, "review_count": 723},
            {"source": "google", "source_label": "Google", "rating": 4.1, "review_count": 2345},
            {"source": "hotpepper", "source_label": "ホットペッパー", "rating": 3.9, "review_count": 1567},
        ],
        "reservation_status": "available",
        "reservation_label": "予約可能",
        "open_hours": "11:00〜24:00",
        "closed_days": "無休",
        "capacity": 100,
        "has_private_room": True,
        "smoking": "分煙",
        "description": "本場韓国の味をそのままに。厚切りサムギョプサルと豊富な一品料理が人気。",
        "features": ["食べ放題あり", "飲み放題あり", "深夜営業"],
        "distance_meters": 0,
        "walk_minutes": 0,
    },
    {
        "id": "r007",
        "name": "天ぷら 近藤",
        "genre": "和食",
        "sub_genre": "天ぷら",
        "area": "銀座",
        "address": "東京都中央区銀座5-5-13",
        "lat": 35.6710,
        "lng": 139.7649,
        "price_min": 12000,
        "price_max": 25000,
        "price_label": "¥12,000〜¥25,000",
        "atmosphere_tags": ["高級感", "落ち着いた", "静か"],
        "photos": [],
        "reviews": [
            {"source": "tabelog", "source_label": "食べログ", "rating": 4.45, "review_count": 567},
            {"source": "google", "source_label": "Google", "rating": 4.5, "review_count": 1432},
            {"source": "hotpepper", "source_label": "ホットペッパー", "rating": 4.3, "review_count": 178},
        ],
        "reservation_status": "few",
        "reservation_label": "残りわずか",
        "open_hours": "12:00〜13:30 / 17:00〜21:00",
        "closed_days": "日曜",
        "capacity": 20,
        "has_private_room": True,
        "smoking": "禁煙",
        "description": "銀座の名店。野菜天ぷらの概念を変える、素材の旨みを引き出す匠の技。",
        "features": ["ミシュラン二つ星", "カウンター", "おまかせコース"],
        "distance_meters": 0,
        "walk_minutes": 0,
    },
    {
        "id": "r008",
        "name": "NARISAWA",
        "genre": "フレンチ",
        "sub_genre": "イノベーティブ",
        "area": "青山",
        "address": "東京都港区南青山2-6-15",
        "lat": 35.6700,
        "lng": 139.7216,
        "price_min": 20000,
        "price_max": 40000,
        "price_label": "¥20,000〜¥40,000",
        "atmosphere_tags": ["高級感", "モダン", "デート向き", "静か"],
        "photos": [],
        "reviews": [
            {"source": "tabelog", "source_label": "食べログ", "rating": 4.55, "review_count": 743},
            {"source": "google", "source_label": "Google", "rating": 4.7, "review_count": 2100},
            {"source": "hotpepper", "source_label": "ホットペッパー", "rating": 4.4, "review_count": 156},
        ],
        "reservation_status": "full",
        "reservation_label": "満席",
        "open_hours": "12:00〜13:00 / 18:00〜21:00",
        "closed_days": "日曜・月曜",
        "capacity": 28,
        "has_private_room": True,
        "smoking": "禁煙",
        "description": "世界のベストレストラン50常連。自然と革新が融合するイノベーティブフレンチ。",
        "features": ["世界ランキング入り", "完全予約制", "ペアリングコース"],
        "distance_meters": 0,
        "walk_minutes": 0,
    },
    {
        "id": "r009",
        "name": "麺屋 翔 新宿本店",
        "genre": "ラーメン",
        "sub_genre": "塩ラーメン",
        "area": "新宿",
        "address": "東京都新宿区西新宿7-22-34",
        "lat": 35.6940,
        "lng": 139.6977,
        "price_min": 800,
        "price_max": 1500,
        "price_label": "¥800〜¥1,500",
        "atmosphere_tags": ["カジュアル", "にぎやか"],
        "photos": [],
        "reviews": [
            {"source": "tabelog", "source_label": "食べログ", "rating": 3.72, "review_count": 1234},
            {"source": "google", "source_label": "Google", "rating": 4.2, "review_count": 4567},
            {"source": "hotpepper", "source_label": "ホットペッパー", "rating": 3.8, "review_count": 432},
        ],
        "reservation_status": "available",
        "reservation_label": "予約不要",
        "open_hours": "11:00〜23:00",
        "closed_days": "無休",
        "capacity": 18,
        "has_private_room": False,
        "smoking": "禁煙",
        "description": "鶏と魚介のWスープが絶品。ミシュランビブグルマンにも選出された塩ラーメンの名店。",
        "features": ["ミシュランビブグルマン", "行列必至", "カウンターのみ"],
        "distance_meters": 0,
        "walk_minutes": 0,
    },
    {
        "id": "r010",
        "name": "炭火焼鳥 よし鳥",
        "genre": "居酒屋",
        "sub_genre": "焼鳥",
        "area": "恵比寿",
        "address": "東京都渋谷区恵比寿1-8-11",
        "lat": 35.6468,
        "lng": 139.7103,
        "price_min": 4000,
        "price_max": 7000,
        "price_label": "¥4,000〜¥7,000",
        "atmosphere_tags": ["アットホーム", "落ち着いた", "隠れ家"],
        "photos": [],
        "reviews": [
            {"source": "tabelog", "source_label": "食べログ", "rating": 3.68, "review_count": 445},
            {"source": "google", "source_label": "Google", "rating": 4.3, "review_count": 876},
            {"source": "hotpepper", "source_label": "ホットペッパー", "rating": 4.0, "review_count": 234},
        ],
        "reservation_status": "available",
        "reservation_label": "予約可能",
        "open_hours": "17:00〜23:30",
        "closed_days": "日曜",
        "capacity": 30,
        "has_private_room": False,
        "smoking": "分煙",
        "description": "備長炭で丁寧に焼き上げる地鶏焼鳥。日本酒との相性も抜群。",
        "features": ["地鶏使用", "日本酒充実", "炭火焼き"],
        "distance_meters": 0,
        "walk_minutes": 0,
    },
    {
        "id": "r011",
        "name": "バンコクキッチン 池袋店",
        "genre": "タイ料理",
        "sub_genre": "タイ家庭料理",
        "area": "池袋",
        "address": "東京都豊島区西池袋3-27-3",
        "lat": 35.7295,
        "lng": 139.7109,
        "price_min": 2000,
        "price_max": 4000,
        "price_label": "¥2,000〜¥4,000",
        "atmosphere_tags": ["カジュアル", "にぎやか", "アットホーム"],
        "photos": [],
        "reviews": [
            {"source": "tabelog", "source_label": "食べログ", "rating": 3.52, "review_count": 389},
            {"source": "google", "source_label": "Google", "rating": 4.0, "review_count": 1567},
            {"source": "hotpepper", "source_label": "ホットペッパー", "rating": 3.7, "review_count": 678},
        ],
        "reservation_status": "available",
        "reservation_label": "予約可能",
        "open_hours": "11:00〜23:00",
        "closed_days": "無休",
        "capacity": 60,
        "has_private_room": False,
        "smoking": "禁煙",
        "description": "本場タイ人シェフが作る本格タイ料理。パッタイとグリーンカレーが大人気。",
        "features": ["ランチセットあり", "テイクアウト可", "辛さ調節可"],
        "distance_meters": 0,
        "walk_minutes": 0,
    },
    {
        "id": "r012",
        "name": "スパイスラボ トーキョー",
        "genre": "インド料理",
        "sub_genre": "モダンインディアン",
        "area": "銀座",
        "address": "東京都中央区銀座6-10-1",
        "lat": 35.6699,
        "lng": 139.7630,
        "price_min": 8000,
        "price_max": 15000,
        "price_label": "¥8,000〜¥15,000",
        "atmosphere_tags": ["おしゃれ", "モダン", "デート向き"],
        "photos": [],
        "reviews": [
            {"source": "tabelog", "source_label": "食べログ", "rating": 3.95, "review_count": 287},
            {"source": "google", "source_label": "Google", "rating": 4.3, "review_count": 743},
            {"source": "hotpepper", "source_label": "ホットペッパー", "rating": 4.1, "review_count": 156},
        ],
        "reservation_status": "available",
        "reservation_label": "予約可能",
        "open_hours": "11:30〜14:00 / 17:30〜22:00",
        "closed_days": "月曜",
        "capacity": 40,
        "has_private_room": True,
        "smoking": "禁煙",
        "description": "伝統スパイスとモダンな技法が融合。今までにないインド料理体験。",
        "features": ["コース料理", "ワインペアリング", "ベジタリアン対応"],
        "distance_meters": 0,
        "walk_minutes": 0,
    },
    {
        "id": "r013",
        "name": "鉄板焼き 銀明翠 銀座",
        "genre": "鉄板焼き",
        "sub_genre": "黒毛和牛鉄板焼き",
        "area": "銀座",
        "address": "東京都中央区銀座8-9-15",
        "lat": 35.6689,
        "lng": 139.7611,
        "price_min": 15000,
        "price_max": 30000,
        "price_label": "¥15,000〜¥30,000",
        "atmosphere_tags": ["高級感", "デート向き", "夜景が見える", "静か"],
        "photos": [],
        "reviews": [
            {"source": "tabelog", "source_label": "食べログ", "rating": 4.22, "review_count": 398},
            {"source": "google", "source_label": "Google", "rating": 4.4, "review_count": 876},
            {"source": "hotpepper", "source_label": "ホットペッパー", "rating": 4.2, "review_count": 210},
        ],
        "reservation_status": "few",
        "reservation_label": "残りわずか",
        "open_hours": "17:00〜22:00",
        "closed_days": "日曜",
        "capacity": 24,
        "has_private_room": True,
        "smoking": "禁煙",
        "description": "目の前で焼き上げる極上の黒毛和牛。銀座の夜景と共に特別なひとときを。",
        "features": ["目の前調理", "記念日対応", "夜景"],
        "distance_meters": 0,
        "walk_minutes": 0,
    },
    {
        "id": "r014",
        "name": "カフェ ランバン",
        "genre": "カフェ",
        "sub_genre": "自家焙煎カフェ",
        "area": "中目黒",
        "address": "東京都目黒区上目黒2-9-1",
        "lat": 35.6440,
        "lng": 139.6986,
        "price_min": 1000,
        "price_max": 2500,
        "price_label": "¥1,000〜¥2,500",
        "atmosphere_tags": ["おしゃれ", "落ち着いた", "テラス席あり"],
        "photos": [],
        "reviews": [
            {"source": "tabelog", "source_label": "食べログ", "rating": 3.60, "review_count": 256},
            {"source": "google", "source_label": "Google", "rating": 4.4, "review_count": 1234},
            {"source": "hotpepper", "source_label": "ホットペッパー", "rating": 4.0, "review_count": 345},
        ],
        "reservation_status": "available",
        "reservation_label": "予約不要",
        "open_hours": "9:00〜21:00",
        "closed_days": "火曜",
        "capacity": 35,
        "has_private_room": False,
        "smoking": "禁煙",
        "description": "自家焙煎のスペシャルティコーヒーと手作りスイーツ。川沿いの開放的な空間。",
        "features": ["自家焙煎", "スイーツ充実", "Wi-Fi完備"],
        "distance_meters": 0,
        "walk_minutes": 0,
    },
    {
        "id": "r015",
        "name": "バル エスパニョール",
        "genre": "スペイン料理",
        "sub_genre": "タパス・バル",
        "area": "恵比寿",
        "address": "東京都渋谷区恵比寿4-3-1",
        "lat": 35.6460,
        "lng": 139.7130,
        "price_min": 4000,
        "price_max": 7000,
        "price_label": "¥4,000〜¥7,000",
        "atmosphere_tags": ["にぎやか", "カジュアル", "おしゃれ", "テラス席あり"],
        "photos": [],
        "reviews": [
            {"source": "tabelog", "source_label": "食べログ", "rating": 3.65, "review_count": 534},
            {"source": "google", "source_label": "Google", "rating": 4.2, "review_count": 1678},
            {"source": "hotpepper", "source_label": "ホットペッパー", "rating": 4.0, "review_count": 789},
        ],
        "reservation_status": "available",
        "reservation_label": "予約可能",
        "open_hours": "17:00〜翌1:00",
        "closed_days": "無休",
        "capacity": 55,
        "has_private_room": False,
        "smoking": "分煙",
        "description": "本場スペインのタパスとワインが楽しめる陽気なバル。パエリアは必食。",
        "features": ["ワイン100種以上", "深夜営業", "パエリア"],
        "distance_meters": 0,
        "walk_minutes": 0,
    },
    {
        "id": "r016",
        "name": "割烹 青華こばやし",
        "genre": "和食",
        "sub_genre": "割烹",
        "area": "麻布十番",
        "address": "東京都港区麻布十番2-7-14",
        "lat": 35.6546,
        "lng": 139.7368,
        "price_min": 10000,
        "price_max": 18000,
        "price_label": "¥10,000〜¥18,000",
        "atmosphere_tags": ["和モダン", "落ち着いた", "隠れ家", "静か"],
        "photos": [],
        "reviews": [
            {"source": "tabelog", "source_label": "食べログ", "rating": 4.30, "review_count": 523},
            {"source": "google", "source_label": "Google", "rating": 4.5, "review_count": 678},
            {"source": "hotpepper", "source_label": "ホットペッパー", "rating": 4.3, "review_count": 145},
        ],
        "reservation_status": "few",
        "reservation_label": "残りわずか",
        "open_hours": "17:30〜22:00",
        "closed_days": "日曜・祝日",
        "capacity": 18,
        "has_private_room": True,
        "smoking": "禁煙",
        "description": "季節の素材を活かした繊細な割烹料理。一品一品に匠の技が光る隠れ家的名店。",
        "features": ["おまかせコース", "日本酒厳選", "カウンター席"],
        "distance_meters": 0,
        "walk_minutes": 0,
    },
    {
        "id": "r017",
        "name": "焼肉 うしごろ 渋谷店",
        "genre": "焼肉",
        "sub_genre": "黒毛和牛",
        "area": "渋谷",
        "address": "東京都渋谷区道玄坂1-5-2",
        "lat": 35.6590,
        "lng": 139.6985,
        "price_min": 10000,
        "price_max": 18000,
        "price_label": "¥10,000〜¥18,000",
        "atmosphere_tags": ["おしゃれ", "デート向き", "モダン"],
        "photos": [],
        "reviews": [
            {"source": "tabelog", "source_label": "食べログ", "rating": 3.90, "review_count": 876},
            {"source": "google", "source_label": "Google", "rating": 4.4, "review_count": 2345},
            {"source": "hotpepper", "source_label": "ホットペッパー", "rating": 4.2, "review_count": 567},
        ],
        "reservation_status": "few",
        "reservation_label": "残りわずか",
        "open_hours": "17:00〜23:00",
        "closed_days": "不定休",
        "capacity": 50,
        "has_private_room": True,
        "smoking": "禁煙",
        "description": "上質な黒毛和牛をおしゃれな空間で。コース仕立ての焼肉で特別な夜を。",
        "features": ["コース焼肉", "ワイン充実", "デート向き"],
        "distance_meters": 0,
        "walk_minutes": 0,
    },
    {
        "id": "r018",
        "name": "中華蕎麦 とみ田",
        "genre": "ラーメン",
        "sub_genre": "つけ麺",
        "area": "新宿",
        "address": "東京都新宿区新宿3-14-20",
        "lat": 35.6906,
        "lng": 139.7005,
        "price_min": 1000,
        "price_max": 2000,
        "price_label": "¥1,000〜¥2,000",
        "atmosphere_tags": ["カジュアル", "にぎやか"],
        "photos": [],
        "reviews": [
            {"source": "tabelog", "source_label": "食べログ", "rating": 3.82, "review_count": 2134},
            {"source": "google", "source_label": "Google", "rating": 4.3, "review_count": 5678},
            {"source": "hotpepper", "source_label": "ホットペッパー", "rating": 4.0, "review_count": 345},
        ],
        "reservation_status": "available",
        "reservation_label": "予約不要",
        "open_hours": "11:00〜21:00",
        "closed_days": "水曜",
        "capacity": 20,
        "has_private_room": False,
        "smoking": "禁煙",
        "description": "超濃厚魚介豚骨つけ麺の王者。行列ができてでも食べたい一杯。",
        "features": ["行列必至", "大盛り無料", "限定メニューあり"],
        "distance_meters": 0,
        "walk_minutes": 0,
    },
    {
        "id": "r019",
        "name": "トラットリア ダル・ビルバンテ・ジョコンド",
        "genre": "イタリアン",
        "sub_genre": "トラットリア",
        "area": "目黒",
        "address": "東京都目黒区目黒3-1-4",
        "lat": 35.6335,
        "lng": 139.7129,
        "price_min": 5000,
        "price_max": 8000,
        "price_label": "¥5,000〜¥8,000",
        "atmosphere_tags": ["アットホーム", "カジュアル", "おしゃれ"],
        "photos": [],
        "reviews": [
            {"source": "tabelog", "source_label": "食べログ", "rating": 3.75, "review_count": 412},
            {"source": "google", "source_label": "Google", "rating": 4.3, "review_count": 987},
            {"source": "hotpepper", "source_label": "ホットペッパー", "rating": 4.1, "review_count": 234},
        ],
        "reservation_status": "available",
        "reservation_label": "予約可能",
        "open_hours": "11:30〜14:00 / 18:00〜22:00",
        "closed_days": "火曜",
        "capacity": 38,
        "has_private_room": False,
        "smoking": "禁煙",
        "description": "地元に愛されるイタリアン。手打ちパスタと季節の食材を使った温かい料理。",
        "features": ["手打ちパスタ", "ワイン充実", "アットホーム"],
        "distance_meters": 0,
        "walk_minutes": 0,
    },
    {
        "id": "r020",
        "name": "赤坂 菊乃井",
        "genre": "和食",
        "sub_genre": "懐石料理",
        "area": "赤坂",
        "address": "東京都港区赤坂6-13-8",
        "lat": 35.6728,
        "lng": 139.7332,
        "price_min": 15000,
        "price_max": 35000,
        "price_label": "¥15,000〜¥35,000",
        "atmosphere_tags": ["高級感", "和モダン", "静か", "個室あり"],
        "photos": [],
        "reviews": [
            {"source": "tabelog", "source_label": "食べログ", "rating": 4.48, "review_count": 612},
            {"source": "google", "source_label": "Google", "rating": 4.6, "review_count": 1543},
            {"source": "hotpepper", "source_label": "ホットペッパー", "rating": 4.4, "review_count": 198},
        ],
        "reservation_status": "full",
        "reservation_label": "満席",
        "open_hours": "12:00〜13:00 / 17:00〜21:00",
        "closed_days": "日曜",
        "capacity": 50,
        "has_private_room": True,
        "smoking": "禁煙",
        "description": "京都の名店が赤坂に。四季折々の懐石料理を洗練された空間で。ミシュラン二つ星。",
        "features": ["ミシュラン二つ星", "懐石コース", "個室完備"],
        "distance_meters": 0,
        "walk_minutes": 0,
    },
    {
        "id": "r021",
        "name": "大衆酒場 ホルモンまさる",
        "genre": "居酒屋",
        "sub_genre": "ホルモン・もつ焼き",
        "area": "池袋",
        "address": "東京都豊島区東池袋1-34-5",
        "lat": 35.7318,
        "lng": 139.7148,
        "price_min": 2000,
        "price_max": 4000,
        "price_label": "¥2,000〜¥4,000",
        "atmosphere_tags": ["にぎやか", "カジュアル", "アットホーム"],
        "photos": [],
        "reviews": [
            {"source": "tabelog", "source_label": "食べログ", "rating": 3.58, "review_count": 678},
            {"source": "google", "source_label": "Google", "rating": 4.1, "review_count": 2345},
            {"source": "hotpepper", "source_label": "ホットペッパー", "rating": 3.8, "review_count": 1234},
        ],
        "reservation_status": "available",
        "reservation_label": "予約可能",
        "open_hours": "16:00〜24:00",
        "closed_days": "無休",
        "capacity": 45,
        "has_private_room": False,
        "smoking": "喫煙可",
        "description": "新鮮ホルモンとレモンサワーで乾杯！コスパ最強の大衆酒場。",
        "features": ["コスパ抜群", "飲み放題あり", "深夜営業"],
        "distance_meters": 0,
        "walk_minutes": 0,
    },
    {
        "id": "r022",
        "name": "エリゼ光",
        "genre": "フレンチ",
        "sub_genre": "クラシックフレンチ",
        "area": "白金",
        "address": "東京都港区白金台5-4-7",
        "lat": 35.6396,
        "lng": 139.7260,
        "price_min": 12000,
        "price_max": 25000,
        "price_label": "¥12,000〜¥25,000",
        "atmosphere_tags": ["高級感", "落ち着いた", "デート向き"],
        "photos": [],
        "reviews": [
            {"source": "tabelog", "source_label": "食べログ", "rating": 4.08, "review_count": 345},
            {"source": "google", "source_label": "Google", "rating": 4.4, "review_count": 567},
            {"source": "hotpepper", "source_label": "ホットペッパー", "rating": 4.2, "review_count": 123},
        ],
        "reservation_status": "available",
        "reservation_label": "予約可能",
        "open_hours": "12:00〜14:00 / 18:00〜21:30",
        "closed_days": "水曜",
        "capacity": 30,
        "has_private_room": True,
        "smoking": "禁煙",
        "description": "白金の閑静な住宅街に佇むクラシックフレンチ。正統派の味わいを。",
        "features": ["ソムリエ常駐", "記念日対応", "庭園あり"],
        "distance_meters": 0,
        "walk_minutes": 0,
    },
    {
        "id": "r023",
        "name": "四川飯店 赤坂",
        "genre": "中華",
        "sub_genre": "四川料理",
        "area": "赤坂",
        "address": "東京都港区赤坂1-12-33",
        "lat": 35.6749,
        "lng": 139.7400,
        "price_min": 5000,
        "price_max": 10000,
        "price_label": "¥5,000〜¥10,000",
        "atmosphere_tags": ["落ち着いた", "個室あり", "高級感"],
        "photos": [],
        "reviews": [
            {"source": "tabelog", "source_label": "食べログ", "rating": 3.88, "review_count": 789},
            {"source": "google", "source_label": "Google", "rating": 4.2, "review_count": 2456},
            {"source": "hotpepper", "source_label": "ホットペッパー", "rating": 4.0, "review_count": 567},
        ],
        "reservation_status": "available",
        "reservation_label": "予約可能",
        "open_hours": "11:30〜14:00 / 17:00〜22:00",
        "closed_days": "無休",
        "capacity": 80,
        "has_private_room": True,
        "smoking": "禁煙",
        "description": "陳建民の流れを汲む本格四川料理。麻婆豆腐は必食の看板メニュー。",
        "features": ["麻婆豆腐", "個室あり", "ランチコース"],
        "distance_meters": 0,
        "walk_minutes": 0,
    },
    {
        "id": "r024",
        "name": "ソウルフードバンコク 表参道",
        "genre": "タイ料理",
        "sub_genre": "モダンタイ",
        "area": "表参道",
        "address": "東京都渋谷区神宮前5-10-1",
        "lat": 35.6637,
        "lng": 139.7098,
        "price_min": 3000,
        "price_max": 6000,
        "price_label": "¥3,000〜¥6,000",
        "atmosphere_tags": ["おしゃれ", "モダン", "テラス席あり"],
        "photos": [],
        "reviews": [
            {"source": "tabelog", "source_label": "食べログ", "rating": 3.62, "review_count": 298},
            {"source": "google", "source_label": "Google", "rating": 4.2, "review_count": 876},
            {"source": "hotpepper", "source_label": "ホットペッパー", "rating": 3.9, "review_count": 345},
        ],
        "reservation_status": "available",
        "reservation_label": "予約可能",
        "open_hours": "11:30〜22:00",
        "closed_days": "無休",
        "capacity": 50,
        "has_private_room": False,
        "smoking": "禁煙",
        "description": "おしゃれな空間で楽しむモダンタイ料理。SNS映えするプレゼンテーションも人気。",
        "features": ["テラス席", "ランチあり", "SNS映え"],
        "distance_meters": 0,
        "walk_minutes": 0,
    },
    {
        "id": "r025",
        "name": "銀座 久兵衛 本店",
        "genre": "寿司",
        "sub_genre": "江戸前寿司",
        "area": "銀座",
        "address": "東京都中央区銀座8-7-6",
        "lat": 35.6694,
        "lng": 139.7620,
        "price_min": 12000,
        "price_max": 25000,
        "price_label": "¥12,000〜¥25,000",
        "atmosphere_tags": ["高級感", "落ち着いた", "静か"],
        "photos": [],
        "reviews": [
            {"source": "tabelog", "source_label": "食べログ", "rating": 4.35, "review_count": 1234},
            {"source": "google", "source_label": "Google", "rating": 4.5, "review_count": 3456},
            {"source": "hotpepper", "source_label": "ホットペッパー", "rating": 4.3, "review_count": 456},
        ],
        "reservation_status": "few",
        "reservation_label": "残りわずか",
        "open_hours": "11:30〜14:00 / 17:00〜22:00",
        "closed_days": "無休",
        "capacity": 55,
        "has_private_room": True,
        "smoking": "禁煙",
        "description": "銀座を代表する老舗寿司店。80年以上の歴史が紡ぐ至高の江戸前寿司。",
        "features": ["老舗", "個室あり", "ランチ営業"],
        "distance_meters": 0,
        "walk_minutes": 0,
    },
    {
        "id": "r026",
        "name": "居酒屋 てっぺん 渋谷店",
        "genre": "居酒屋",
        "sub_genre": "創作居酒屋",
        "area": "渋谷",
        "address": "東京都渋谷区宇田川町31-1",
        "lat": 35.6614,
        "lng": 139.6977,
        "price_min": 3000,
        "price_max": 5000,
        "price_label": "¥3,000〜¥5,000",
        "atmosphere_tags": ["にぎやか", "カジュアル", "大人数OK"],
        "photos": [],
        "reviews": [
            {"source": "tabelog", "source_label": "食べログ", "rating": 3.45, "review_count": 567},
            {"source": "google", "source_label": "Google", "rating": 3.9, "review_count": 1987},
            {"source": "hotpepper", "source_label": "ホットペッパー", "rating": 3.7, "review_count": 2345},
        ],
        "reservation_status": "available",
        "reservation_label": "予約可能",
        "open_hours": "17:00〜翌5:00",
        "closed_days": "無休",
        "capacity": 120,
        "has_private_room": True,
        "smoking": "分煙",
        "description": "朝5時まで営業！豊富なメニューと飲み放題で盛り上がる定番居酒屋。",
        "features": ["朝まで営業", "飲み放題", "大人数対応"],
        "distance_meters": 0,
        "walk_minutes": 0,
    },
    {
        "id": "r027",
        "name": "焼肉 TORAJI 恵比寿本店",
        "genre": "焼肉",
        "sub_genre": "韓国式焼肉",
        "area": "恵比寿",
        "address": "東京都渋谷区恵比寿1-29-16",
        "lat": 35.6480,
        "lng": 139.7090,
        "price_min": 6000,
        "price_max": 12000,
        "price_label": "¥6,000〜¥12,000",
        "atmosphere_tags": ["おしゃれ", "デート向き", "モダン", "個室あり"],
        "photos": [],
        "reviews": [
            {"source": "tabelog", "source_label": "食べログ", "rating": 3.70, "review_count": 934},
            {"source": "google", "source_label": "Google", "rating": 4.2, "review_count": 3456},
            {"source": "hotpepper", "source_label": "ホットペッパー", "rating": 4.0, "review_count": 1876},
        ],
        "reservation_status": "available",
        "reservation_label": "予約可能",
        "open_hours": "17:00〜23:30",
        "closed_days": "無休",
        "capacity": 90,
        "has_private_room": True,
        "smoking": "禁煙",
        "description": "洗練された空間で楽しむ上質焼肉。特選カルビとユッケは絶品。",
        "features": ["個室充実", "コース料理", "記念日対応"],
        "distance_meters": 0,
        "walk_minutes": 0,
    },
    {
        "id": "r028",
        "name": "ピッツェリア エ トラットリア ダ イーサ",
        "genre": "イタリアン",
        "sub_genre": "ナポリピッツァ",
        "area": "中目黒",
        "address": "東京都目黒区青葉台1-28-9",
        "lat": 35.6485,
        "lng": 139.6940,
        "price_min": 2000,
        "price_max": 5000,
        "price_label": "¥2,000〜¥5,000",
        "atmosphere_tags": ["カジュアル", "にぎやか", "アットホーム"],
        "photos": [],
        "reviews": [
            {"source": "tabelog", "source_label": "食べログ", "rating": 3.80, "review_count": 1456},
            {"source": "google", "source_label": "Google", "rating": 4.4, "review_count": 4321},
            {"source": "hotpepper", "source_label": "ホットペッパー", "rating": 4.1, "review_count": 678},
        ],
        "reservation_status": "available",
        "reservation_label": "予約不要",
        "open_hours": "11:30〜15:00 / 18:00〜22:30",
        "closed_days": "火曜",
        "capacity": 40,
        "has_private_room": False,
        "smoking": "禁煙",
        "description": "世界大会優勝のピッツァイオーロが焼く本場ナポリピッツァ。もちもち生地が絶品。",
        "features": ["世界大会優勝", "薪窯焼き", "行列人気店"],
        "distance_meters": 0,
        "walk_minutes": 0,
    },
    {
        "id": "r029",
        "name": "丸の内 TOKIA ダイニング",
        "genre": "ビストロ",
        "sub_genre": "モダンビストロ",
        "area": "丸の内",
        "address": "東京都千代田区丸の内2-7-3",
        "lat": 35.6793,
        "lng": 139.7649,
        "price_min": 5000,
        "price_max": 10000,
        "price_label": "¥5,000〜¥10,000",
        "atmosphere_tags": ["おしゃれ", "モダン", "夜景が見える", "デート向き"],
        "photos": [],
        "reviews": [
            {"source": "tabelog", "source_label": "食べログ", "rating": 3.72, "review_count": 456},
            {"source": "google", "source_label": "Google", "rating": 4.1, "review_count": 1234},
            {"source": "hotpepper", "source_label": "ホットペッパー", "rating": 4.0, "review_count": 567},
        ],
        "reservation_status": "available",
        "reservation_label": "予約可能",
        "open_hours": "11:30〜14:30 / 17:30〜23:00",
        "closed_days": "無休",
        "capacity": 65,
        "has_private_room": True,
        "smoking": "禁煙",
        "description": "丸の内の夜景を一望できるモダンビストロ。洗練された料理とワインのマリアージュ。",
        "features": ["夜景", "ワイン充実", "ランチ営業"],
        "distance_meters": 0,
        "walk_minutes": 0,
    },
    {
        "id": "r030",
        "name": "韓国料理 プロカンジャンケジャン",
        "genre": "韓国料理",
        "sub_genre": "カンジャンケジャン",
        "area": "新宿",
        "address": "東京都新宿区大久保1-7-1",
        "lat": 35.6989,
        "lng": 139.7047,
        "price_min": 5000,
        "price_max": 8000,
        "price_label": "¥5,000〜¥8,000",
        "atmosphere_tags": ["カジュアル", "にぎやか", "アットホーム"],
        "photos": [],
        "reviews": [
            {"source": "tabelog", "source_label": "食べログ", "rating": 3.72, "review_count": 567},
            {"source": "google", "source_label": "Google", "rating": 4.3, "review_count": 2345},
            {"source": "hotpepper", "source_label": "ホットペッパー", "rating": 4.1, "review_count": 876},
        ],
        "reservation_status": "available",
        "reservation_label": "予約可能",
        "open_hours": "11:30〜22:00",
        "closed_days": "無休",
        "capacity": 70,
        "has_private_room": True,
        "smoking": "禁煙",
        "description": "韓国で大人気のカンジャンケジャン専門店が東京に。ご飯泥棒と呼ばれる絶品蟹料理。",
        "features": ["カンジャンケジャン", "コース料理", "個室あり"],
        "distance_meters": 0,
        "walk_minutes": 0,
    },
]
